# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'AWSSNS-Sample' do
pod 'AWSCore', '~> 2.2.0'
pod 'AWSCognito', '~> 2.2.0'
pod 'AWSSNS', '~> 2.2.0'
end

target 'AWSSNS-SampleTests' do

end

target 'AWSSNS-SampleUITests' do

end

